# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: 'OSPO License scan action'
description: 'A GitHub Action to scan for licenses in your code.'
runs:
  using: "composite"
  steps:
    - name: Analyze
      # TODO: what is a logical location to place the files?
      shell: bash
      run: |
        set -o xtrace
        mkdir -p ${{ github.workspace }}/ort/results

        docker run --rm \
        -v ${{ github.workspace }}:/project \
        -v $NPM_CONFIG_USERCONFIG:/root/.npmrc \
        -e NODE_AUTH_TOKEN philipssoftware/ort:latest \
        --info \
        analyze \
        -i /project \
        -o /project/ort \
        --package-curations-file /project/curations.yml

        cp ${{ github.workspace }}/ort/analyzer-result.yml ${{ github.workspace }}/ort/results/
    - name: Evaluate
      # TODO: make optional while maintaining in- and output file chain
      # TODO: enable dynamically downloading evaluation rules and classifications
      shell: bash
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/project \
        philipssoftware/ort:latest \
        --info \
        evaluate \
        -i /project/ort/analyzer-result.yml \
        -o /project/ort \
        --license-classifications-file /project/ort-license-classifications.yml \
        --rules-file /project/ort-rules.kts
        --package-curations-file /project/curations.yml

        cp ${{ github.workspace }}/ort/evaluation-result.yml ${{ github.workspace }}/ort/results/
    - name: Report
      # TODO: make reports configurable
      shell: bash
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/project \
        -v $NPM_CONFIG_USERCONFIG:/root/.npmrc \
        philipssoftware/ort:latest \
        --info \
        report \
        -f SpdxDocument,StaticHtml,WebApp \
        -i /project/ort/evaluation-result.yml \
        -o /project/ort/reports

        cp -r ${{ github.workspace }}/ort/reports ${{ github.workspace }}/ort/results/
