name: 'OSPO License scan action'
description: 'A GitHub Action created by the Alliander Open Source Program Office (OSPO) to scan for licenses in your code.'
runs:
  using: "composite"
  steps:
    - name: Analyze
      shell: bash
      run: |
        set -o xtrace
        mkdir -p ${{ github.workspace }}/ort/results

        docker run \
        -v ${{ github.workspace }}:/project \
        -v $NPM_CONFIG_USERCONFIG:/root/.npmrc \
        -e NODE_AUTH_TOKEN philipssoftware/ort:latest \
        --info \
        analyze \
        -i /project \
        -o /project/ort \
        --package-curations-file /project/curations.yml

        cp ${{ github.workspace }}/ort/analyzer-result.yml ${{ github.workspace }}/ort/results/
